# Base configs
baseurl:

# UI configs
title: "DC"
author: "DC"
about: "A Photographer"
social_urls:
  facebook: "https://www.facebook.com/dhuv3n"
  twitter: "https://www.twitter.com/mistryvatsal11"
  instagram: "https://www.instagram.com/dsinh8314"
